apiVersion: v1
kind: ReplicationController
metadata:
  name: customer-s
  namespace: kube-system
  labels:
    name: customer-s
spec:
  replicas: 1
  selector:
    name: customer-s
  template:
    metadata:
      labels: 
        name: customer-s
    spec:
      restartPolicy: Always
      containers:
      - name: customer-s
        image: registry:5000/library/customer-service:BUILDTAG_7.1.1-148-161009
        env: 
          - name: TZ
            value: Asia/Shanghai
        ports:
        - containerPort: 8080
          name: customer-s
          protocol: TCP
      dnsPolicy: ClusterFirst