apiVersion: v1
kind: ReplicationController
metadata:
  name: job-s
  namespace: kube-system
  labels:
    name: job-s
spec:
  replicas: 1
  selector:
    name: job-s
  template:
    metadata:
      labels: 
        name: job-s
    spec:
      restartPolicy: Always
      containers:
      - name: job-s
        image: registry:5000/library/job-service:BUILDTAG_7.1.1-148-161009
        env: 
          - name: TZ
            value: Asia/Shanghai
        ports:
        - containerPort: 8080
          name: job-s
          protocol: TCP
      dnsPolicy: ClusterFirst