apiVersion: v1
kind: ReplicationController
metadata:
  name: platform-cache-config-s
  namespace: kube-system
  labels:
    name: platform-cache-config-s
spec:
  replicas: 1
  selector:
    name: platform-cache-config-s
  template:
    metadata:
      labels: 
        name: platform-cache-config-s
    spec:
      restartPolicy: Always
      containers:
      - name: platform-cache-config-s
        image: registry:5000/library/platform-cache-config:BUILDTAG_7.1.1-148-161009
        env: 
          - name: TZ
            value: Asia/Shanghai
        ports:
        - containerPort: 8080
          name: platform-cache
          protocol: TCP
      dnsPolicy: ClusterFirst