apiVersion: v1
kind: ReplicationController
metadata:
  name: pms-partition-s
  namespace: kube-system
  labels:
    name: pms-partition-s
spec:
  replicas: 1
  selector:
    name: pms-partition-s
  template:
    metadata:
      labels: 
        name: pms-partition-s
    spec:
      restartPolicy: Always
      containers:
      - name: pms-partition-s
        image: registry:5000/library/pms-partition-service:BUILDTAG_7.1.1-148-161009
        env: 
          - name: TZ
            value: Asia/Shanghai
        ports:
        - containerPort: 8080
          name: pms-partition-s
          protocol: TCP
      dnsPolicy: ClusterFirst