apiVersion: v1
kind: ReplicationController
metadata:
  name: redis1
  namespace: kube-system
  labels:
    name: redis1
spec:
  replicas: 1
  selector:
    name: redis1
  template:
    metadata:
      labels: 
        name: redis1
    spec:
      volumes:
      - name: sentinelconf
        hostPath:
          path: /redis/sentinel/sentinel_26379.conf
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      containers:
      - name: redis1
        image: registry:5000/library/redis:basal
        args: ["redis-sentinel", "/usr/local/etc/redis/sentinel_26379.conf"]
        volumeMounts:
          - name: sentinelconf
            mountPath: /usr/local/etc/redis/sentinel_26379.conf
        env:
          - name: TZ
            value: Asia/Shanghai
        ports:
        - containerPort: 26379
          name: redis1
          protocol: TCP