apiVersion: v1
kind: ReplicationController
metadata:
  name: area-service
spec:
  replicas: 1
  template:
    metadata:
      name: area-service
      labels:
        app: area-service
        tier: backend
        type: service
        center: center
        group: stariboss
        version: BUILDTAG_7.1.1-66-160520
    spec:
      containers:
      - name: area-service
        image: registry:5000/area-service:BUILDTAG_7.1.1-66-160520
        env:
        - name: dubbo_registry_address
          value: 10.254.1.3:2181
        resources:
          requests:
            cpu: 1
            memory: 1000Mi
        volumeMounts:
        - mountPath: /etc/localtime
          name: localtime
        ports:
        - containerPort: 8080
      volumes:
       - name: localtime
         hostPath:
           path: /etc/localtime

