apiVersion: v1
kind: Service
metadata:
  name: system-service 
  labels:
    app: system-service
    tier: backend
    type: service
    center: center 
    group: stariboss
spec:
  ports:
    # the port that this service should serve on
  - port: 8080
    targetPort: 8080
  selector:
    app: system-service 
    tier: backend
    group: stariboss
