apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
    role: sentinel
    tier: backend
    group: stariboss
  name: redis-sentinel
spec:
  ports:
    - port: 26379
      targetPort: 26379
  clusterIP: 10.254.1.2
  selector:
    app: redis
    role: sentinel
    tier: backend
    group: stariboss



