apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-slave
spec:
  replicas: 2
  template:
    metadata:
      name: redis-slave
      labels:
        app: redis
        role: slave
        tier: backend
        group: stariboss
    spec:
      containers:
      - name: redis-slave
        image: registry:5000/redis:basal
        args: [ "redis-server", "/config/redis-slave.conf" ]
        resources:
          requests:
            cpu: 1
            memory: 2000Mi
        volumeMounts:
        - mountPath: /etc/localtime
          name: localtime
        - mountPath: /config
          name: config
        ports:
        - containerPort: 6379
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: config
        persistentVolumeClaim:
          claimName: config-pv
