apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
    tier: backend
    group: stariboss
spec:
  ports:
    # the port that this service should serve on
  - name: p6379
    port: 6379
    targetPort: 6379
  clusterIP: 10.254.1.2
  selector:
    app: redis
    role: master
    tier: backend
    group: stariboss

