apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-slave-rdb
spec:
  replicas: 1
  template:
    metadata:
      name: redis-slave-rdb
      labels:
        app: redis
        role: slave-rdb
        tier: backend
        group: stariboss
    spec:
      containers:
      - name: redis-slave-rdb
        image: registry:5000/redis:basal
        args: [ "redis-server","/config/redis-slave-rdb.conf" ]
        resources:
          requests:
            cpu: 1
            memory: 4000Mi
        volumeMounts:
        - mountPath: /etc/localtime
          name: localtime
        - mountPath: /data
          name: data
        - mountPath: /config
          name: config
        ports:
        - containerPort: 6379
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: data
        emptyDir: {}
      - name: config
        persistentVolumeClaim:
          claimName: config-pv
