apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
    tier: backend
    group: stariboss
spec:
  ports:
    # the port that this service should serve on
  - port: 2181
    targetPort: 2181
#    nodePort: 30100
  clusterIP: 10.254.1.3
#  type: NodePort
  externalIPs: ["10.0.251.165"]
  selector:
    app: zookeeper 
    tier: backend
    group: stariboss

