redismaster:
  image: 10.0.251.196/platform/redis:3.0.7
  restart: always
  command: redis-sentinel /usr/local/etc/redis/sentinel_26379.conf
  ports:
  - 26379:26379
  volumes:
  - /home/nfs/redis/sentinel/sentinel_26379.conf:/usr/local/etc/redis/sentinel_26379.conf
  environment:
  - TZ=Asia/Shanghai
  container_name: redissentinel