apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: area-service
  namespace: {NAME_SPACE}
spec:
  replicas: 1
  template:
    metadata:
      labels: 
        name: area-service
        tier: backend
        subsystem: unconfirmed
        version: {VERSION}
        partition: "no"
    spec:
      imagePullSecrets:
      - name: mysecret
      restartPolicy: Always
      containers:
      - name: area-service
        image: 10.0.251.196/boss/area-service:{IMAGE_TAG}
        volumeMounts:
          - mountPath: {NFS_CONTAINER_DIR}
            name: nfs
          - mountPath: /usr/local/tomcat/logs/
            name: tomcatlogs
        imagePullPolicy: Always
        env: 
          - name: TZ
            value: Asia/Shanghai
        ports:
        - containerPort: 8080
          name: area-service
          protocol: TCP
      dnsPolicy: ClusterFirst
      volumes:
      - name: nfs
        hostPath:
          path: {NFS_HOST_DIR}
      - name: tomcatlogs
        hostPath:
          path: {NFS_HOST_DIR}/moduleLogs/area-service/logs/