apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: platform-cache-config
  namespace: {NAME_SPACE}
spec:
  replicas: 1
  template:
    metadata:
      labels: 
        name: platform-cache-config
        tier: backend
        subsystem: unconfirmed
        version: {VERSION}
        partition: "no"
    spec:
      imagePullSecrets:
      - name: mysecret
      restartPolicy: Always
      containers:
      - name: platform-cache-config
        image: 10.0.251.196/boss/platform-cache-config:{IMAGE_TAG}
        volumeMounts:
          - mountPath: /usr/local/platform-cache-config/bin/logs/
            name: tomcatlogs
        imagePullPolicy: Always
        env: 
          - name: TZ
            value: Asia/Shanghai
        ports:
        - containerPort: 8080
          name: platform-c-c
          protocol: TCP
      dnsPolicy: ClusterFirst
      volumes:
      - name: tomcatlogs
        hostPath:
          path: {NFS_HOST_DIR}/moduleLogs/platform-cache-config/logs/