apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zookeeper1
  namespace: {NAME_SPACE}
spec:
  replicas: 1
  template:
    metadata:
      labels: 
        name: zookeeper1
        tier: backend
        subsystem: platform
        version: 3.4.8
        partition: "no"
    spec:
      imagePullSecrets:
      - name: mysecret
      restartPolicy: Always
      containers:
      - name: zookeeper1
        image: 10.0.251.196/platform/zookeeper:3.4.8
        imagePullPolicy: Always
        env: 
          - name: TZ
            value: Asia/Shanghai
        ports:
        - containerPort: 2181
          name: zookeeper1
          protocol: TCP
      dnsPolicy: ClusterFirst