apiVersion: v1
kind: ReplicationController
metadata:
  name: admin-public-ui
  namespace: {NAME_SPACE}
  labels:
    name: admin-public-ui
spec:
  replicas: 1
  selector:
    name: admin-public-ui
  template:
    metadata:
      labels: 
        name: admin-public-ui
    spec:
      imagePullSecrets:
      - name: mysecret
      restartPolicy: Always
      containers:
      - name: admin-public-ui
        image: 10.0.251.196/boss/admin-public-ui:{IMAGE_TAG}
        volumeMounts:
          - mountPath: {NFS_CONTAINER_DIR}
            name: nfs
        imagePullPolicy: Always
        env: 
          - name: TZ
            value: Asia/Shanghai
        ports:
        - containerPort: 8080
          name: a-public-ui
          protocol: TCP
      dnsPolicy: ClusterFirst
      volumes:
      - name: nfs
        hostPath:
          path: {NFS_HOST_DIR}