apiVersion: v1
kind: ReplicationController
metadata:
  name: api
  namespace: {NAME_SPACE}
  labels:
    name: api
spec:
  replicas: 1
  selector:
    name: api
  template:
    metadata:
      labels: 
        name: api
    spec:
      imagePullSecrets:
      - name: mysecret
      restartPolicy: Always
      containers:
      - name: api
        image: 10.0.251.196/boss/api:{IMAGE_TAG}
        volumeMounts:
          - mountPath: {NFS_CONTAINER_DIR}
            name: nfs
        env: 
          - name: TZ
            value: Asia/Shanghai
        ports:
        - containerPort: 8080
          name: api
          protocol: TCP
      dnsPolicy: ClusterFirst
      volumes:
      - name: nfs
        hostPath:
          path: {NFS_HOST_DIR}