apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql
  namespace: {NAME_SPACE}
  labels:
    name: mysql
spec:
  replicas: 1
  selector:
    name: mysql
  template:
    metadata:
      labels: 
        name: mysql
    spec:
      imagePullSecrets:
      - name: mysecret
      restartPolicy: Always
      containers:
      - name: mysql
        image: 10.0.251.196/platform/mysql:5.5.53
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql
        env: 
          - name: TZ
            value: Asia/Shanghai
          - name: MYSQL_ROOT_PASSWORD
            value: "123456"
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
      dnsPolicy: ClusterFirst
      volumes:
      - name: mysql
        hostPath:
          path: {NFS_HOST_DIR}/mysql