apiVersion: v1
kind: ReplicationController
metadata:
  name: note-center-service
  namespace: {NAME_SPACE}
  labels:
    name: note-center-service
spec:
  replicas: 1
  selector:
    name: note-center-service
  template:
    metadata:
      labels: 
        name: note-center-service
    spec:
      imagePullSecrets:
      - name: mysecret
      restartPolicy: Always
      containers:
      - name: note-center-s
        image: 10.0.251.196/boss/note-center-service:{IMAGE_TAG}
        volumeMounts:
          - mountPath: {NFS_CONTAINER_DIR}
            name: nfs
        imagePullPolicy: Always
        env: 
          - name: TZ
            value: Asia/Shanghai
        ports:
        - containerPort: 8080
          name: note-center-s
          protocol: TCP
      dnsPolicy: ClusterFirst
      volumes:
      - name: nfs
        hostPath:
          path: {NFS_HOST_DIR}