apiVersion: v1
kind: ReplicationController
metadata:
  name: order-job
  namespace: {NAME_SPACE}
  labels:
    name: order-job
spec:
  replicas: 1
  selector:
    name: order-job
  template:
    metadata:
      labels: 
        name: order-job
    spec:
      imagePullSecrets:
      - name: mysecret
      restartPolicy: Always
      containers:
      - name: order-j
        image: 10.0.251.196/boss/order-job:{IMAGE_TAG}
        volumeMounts:
          - mountPath: {NFS_CONTAINER_DIR}
            name: nfs
        imagePullPolicy: Always
        env: 
          - name: TZ
            value: Asia/Shanghai
        ports:
        - containerPort: 8080
          name: order-j
          protocol: TCP
      dnsPolicy: ClusterFirst
      volumes:
      - name: nfs
        hostPath:
          path: {NFS_HOST_DIR}