apiVersion: v1
kind: ReplicationController
metadata:
  name: redis1
  namespace: {NAME_SPACE}
  labels:
    name: redis1
spec:
  replicas: 1
  selector:
    name: redis1
  template:
    metadata:
      labels: 
        name: redis1
    spec:
      imagePullSecrets:
      - name: mysecret
      volumes:
      - name: sentinelconf
        hostPath:
          path: {NFS_HOST_DIR}/redis/sentinel/sentinel_26379.conf
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      containers:
      - name: redis1
        image: 10.0.251.196/platform/redis:3.0.7
        imagePullPolicy: Always
        args: ["redis-sentinel", "/usr/local/etc/redis/sentinel_26379.conf"]
        volumeMounts:
          - name: sentinelconf
            mountPath: /usr/local/etc/redis/sentinel_26379.conf
        env:
          - name: TZ
            value: Asia/Shanghai
        ports:
        - containerPort: 26379
          name: redis1
          protocol: TCP