apiVersion: v1
kind: ReplicationController
metadata:
  name: redisslave
  namespace: {NAME_SPACE}
  labels:
    name: redisslave
spec:
  replicas: 1
  selector:
    name: redisslave
  template:
    metadata:
      labels: 
        name: redisslave
    spec:
      imagePullSecrets:
      - name: mysecret
      volumes:
      - name: slaveconf
        hostPath:
          path: {NFS_HOST_DIR}/redis/slave/6381.conf
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      containers:
      - name: redisslave
        image: 10.0.251.196/platform/redis:3.0.7
        imagePullPolicy: Always
        args: ["redis-server", "/usr/local/etc/redis/redis.conf"]
        volumeMounts:
          - name: slaveconf
            mountPath: /usr/local/etc/redis/redis.conf
        env: 
          - name: TZ
            value: Asia/Shanghai
        ports:
        - containerPort: 6381
          name: redisslave
          protocol: TCP