apiVersion: v1
kind: ReplicationController
metadata:
  name: zookeeperui
  namespace: {NAME_SPACE}
  labels:
    name: zookeeperui
spec:
  replicas: 1
  selector:
    name: zookeeperui
  template:
    metadata:
      labels: 
        name: zookeeperui
    spec:
      imagePullSecrets:
      - name: mysecret
      restartPolicy: Always
      containers:
      - name: zookeeperui
        image: 10.0.251.196/platform/zookeeperui:1.0.0
        imagePullPolicy: Always
        command: ["sh"]
        args: ["-c","sed -i -e 's/${ZOOKEEPER_ADDRESS}/zookeeper1/g' /zkui/config.cfg && java -jar /zkui/zkui.jar /zkui/config.cfg"]
        env: 
          - name: TZ
            value: Asia/Shanghai
        ports:
        - containerPort: 9090
          name: zookeeperui
          protocol: TCP
      dnsPolicy: ClusterFirst