apiVersion: v1
kind: ReplicationController
metadata:
  name: zookeeper1
  namespace: {NAME_SPACE}
  labels:
    name: zookeeper1
spec:
  replicas: 1
  selector:
    name: zookeeper1
  template:
    metadata:
      labels: 
        name: zookeeper1
    spec:
      imagePullSecrets:
      - name: mysecret
      restartPolicy: Always
      containers:
      - name: zookeeper1
        image: 10.0.251.196/platform/zookeeper:3.4.8
        imagePullPolicy: Always
        env: 
          - name: TZ
            value: Asia/Shanghai
        ports:
        - containerPort: 2181
          name: zookeeper1
          protocol: TCP
      dnsPolicy: ClusterFirst