apiVersion: v1
kind: Service
metadata:
  name: activiti-rest
  namespace: {NAME_SPACE}
  labels:
    name: activiti-rest
spec:
  selector:
    name: activiti-rest
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30255