apiVersion: v1
kind: Service
metadata:
  name: admin-crm-ui
  namespace: {NAME_SPACE}
  labels:
    name: admin-crm-ui
spec:
  selector:
    name: admin-crm-ui
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30220