apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {NAME_SPACE}
  labels:
    name: api
spec:
  selector:
    name: api
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30216