apiVersion: v1
kind: Service
metadata:
  name: dubbomonitor
  namespace: {NAME_SPACE}
  labels:
    name: dubbomonitor
spec:
  selector:
    name: dubbomonitor
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30209