apiVersion: v1
kind: Service
metadata:
  name: knowledge-ui
  namespace: {NAME_SPACE}
  labels:
    name: knowledge-ui
spec:
  selector:
    name: knowledge-ui
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30236