apiVersion: v1
kind: Service
metadata:
  name: order-job
  namespace: {NAME_SPACE}
  labels:
    name: order-j
spec:
  selector:
    name: order-job
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30256