apiVersion: v1
kind: Service
metadata:
  name: pms-f-c-s
  namespace: {NAME_SPACE}
  labels:
    name: pms-frontend-conax-service
spec:
  selector:
    name: pms-frontend-conax-service
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30253