apiVersion: v1
kind: Service
metadata:
  name: redismaster
  namespace: {NAME_SPACE}
  labels:
    name: redismaster
spec:
  selector:
    name: redismaster
  type: NodePort
  ports:
  - port: 6380
    targetPort: 6380
    nodePort: 30203