apiVersion: v1
kind: Service
metadata:
  name: redis1
  namespace: {NAME_SPACE}
  labels:
    name: redis1
spec:
  selector:
    name: redis1
  type: NodePort
  ports:
  - port: 26379
    targetPort: 26379
    nodePort: 30205