apiVersion: v1
kind: Service
metadata:
  name: redisslave
  namespace: {NAME_SPACE}
  labels:
    name: redisslave
spec:
  selector:
    name: redisslave
  type: NodePort
  ports:
  - port: 6381
    targetPort: 6381
    nodePort: 30206