apiVersion: v1
kind: Service
metadata:
  name: swagger-validator
  namespace: {NAME_SPACE}
  labels:
    name: swagger-validator
spec:
  selector:
    name: swagger-validator
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30208