apiVersion: v1
kind: Service
metadata:
  name: zkdash
  namespace: {NAME_SPACE}
  labels:
    name: zkdash
spec:
  selector:
    name: zkdash
  type: NodePort
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: 30202