apiVersion: v1
kind: Service
metadata:
  name: zookeeperui
  namespace: {NAME_SPACE}
  labels:
    name: zookeeperui
spec:
  selector:
    name: zookeeperui
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30302