apiVersion: v1
kind: Service
metadata:
  name: zookeeper1
  namespace: {NAME_SPACE}
  labels:
    name: zookeeper1
spec:
  selector:
    name: zookeeper1
  type: NodePort
  ports:
  - port: 2181
    targetPort: 2181
    nodePort: 30204
    