apiVersion: v1
kind: Service
metadata:
  name: collection-service
  namespace: kube-system
  labels:
    name: collection-s
spec:
  selector:
    name: collection-service
  ports:
  - port: 8080
    targetPort: 8080