apiVersion: v1
kind: Service
metadata:
  name: pms-partition-service
  namespace: kube-system
  labels:
    name: pms-partition-s
spec:
  selector:
    name: pms-partition-service
  ports:
  - port: 8080
    targetPort: 8080