apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: kube-system
  labels:
    name: product-s
spec:
  selector:
    name: product-service
  ports:
  - port: 8080
    targetPort: 8080