apiVersion: v1
kind: Service
metadata:
  name: redismaster
  namespace: kube-system
  labels:
    name: redismaster
spec:
  selector:
    name: redismaster
  ports:
  - port: 6380
    targetPort: 6380