apiVersion: v1
kind: Service
metadata:
  name: resource-center-service
  namespace: kube-system
  labels:
    name: resource-center-s
spec:
  selector:
    name: resource-center-service
  ports:
  - port: 8080
    targetPort: 8080